"""empty message

Revision ID: 93dbbea6de7e
Revises: 
Create Date: 2024-10-05 11:09:49.761511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dbbea6de7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('login')
    )
    op.create_table('connections',
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('permission',
    sa.Column('allowed', sa.Enum('role_get_all', 'role_create', 'role_update', 'role_delete', 'set_role', 'change_role_for_user', 'check_user_permissions', name='permissionenum'), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('connections')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
